[meta]
seed = 0
use_amp = true
cudnn_enabled = false
use_quant = false
use_prune = false
iter_prune = false
use_kd = false

[path]
# base = "./output/DCCRN"
base = "/model/DCCRN"

[dataloader]
batch_size = [85, 20]
num_workers = 8
drop_last = false
pin_memory = false

[dataset]
sr = 16000
n_fft = 512
win_len = 480
hop_len = 120
audio_len = 3.0
limit = 0

[model]
encoder_decoder_num_channels = [2, 32, 64, 128, 256, 256, 256]
encoder_decoder_kernel_size = 5
rnn_hidden_size = 256
rnn_num_layers = 2
look_ahead = 1

[train]
resume = false
n_folds = 1
n_jobs = 8
optimizer = "Adam"
lr = 1e-3
epochs = 9999
save_checkpoint_interval = 1
valid_interval = 1
clip_grad_norm_value = 10.0
audio_visual_samples = 2

[inference]
n_folds = 1
n_jobs = 8
audio_len = 30.0
audio_visual_samples = 2

[kd.model]
encoder_decoder_num_channels = [2, 16, 32, 64, 128, 128, 128]
encoder_decoder_kernel_size = 5
rnn_hidden_size = 128
rnn_num_layers = 2
look_ahead = 1

[kd.train]
alpha = 0.5
